import React, { useState, useMemo } from 'react';
import { useData } from '../../../context/DataContext';
import { useAuth } from '../../../context/AuthContext';
import { InternalTournament } from '../../../types';
import { NewTournamentModal } from './NewTournamentModal';
import { 
  Trophy, 
  Plus, 
  Calendar, 
  Clock, 
  MapPin, 
  Layers, 
  Users, 
  Swords, 
  CheckCircle2, 
  ChevronRight,
  Sparkles,
  Filter,
  Search,
  Trash2
} from 'lucide-react';

interface TournamentListProps {
  onSelectTournament: (tournament: InternalTournament) => void;
  onNavigateToTimer?: (matchDuration: number, title: string) => void;
}

export const TournamentList: React.FC<TournamentListProps> = ({
  onSelectTournament,
}) => {
  const { tournaments, createTournament, deleteTournament } = useData();
  const { currentUser } = useAuth();

  const [isNewTournamentModalOpen, setIsNewTournamentModalOpen] = useState(false);
  const [statusFilter, setStatusFilter] = useState<'ALL' | 'REGISTRATION' | 'IN_PROGRESS' | 'COMPLETED'>('ALL');
  const [searchQuery, setSearchQuery] = useState('');

  // Confirmation modal state for safe iframe operations
  const [confirmDeleteDialog, setConfirmDeleteDialog] = useState<{
    isOpen: boolean;
    tournamentId: string;
    tournamentTitle: string;
  }>({
    isOpen: false,
    tournamentId: '',
    tournamentTitle: '',
  });

  const canCreate = currentUser?.role === 'ADMIN' || currentUser?.role === 'PROFESSOR';

  // Base list depending on user role:
  // - Teachers/Admins see all tournaments (drafts, registration, active, completed)
  // - Students ONLY see tournaments where brackets have been generated by the professor
  const baseTournaments = useMemo(() => {
    if (canCreate) return tournaments;
    return tournaments.filter((t) =>
      t.categories.some((cat) => cat.matches && cat.matches.length > 0)
    );
  }, [tournaments, canCreate]);

  // Filtered list
  const filteredTournaments = useMemo(() => {
    return baseTournaments.filter((t) => {
      if (statusFilter !== 'ALL' && t.status !== statusFilter) return false;
      if (searchQuery.trim()) {
        const q = searchQuery.toLowerCase();
        return t.title.toLowerCase().includes(q) || (t.location && t.location.toLowerCase().includes(q));
      }
      return true;
    });
  }, [baseTournaments, statusFilter, searchQuery]);

  // General Metrics
  const metrics = useMemo(() => {
    let totalCompetitors = 0;
    let totalMatches = 0;
    let completedMatches = 0;
    let championsCount = 0;

    baseTournaments.forEach(t => {
      t.categories.forEach(cat => {
        totalCompetitors += cat.competitors.length;
        if (cat.matches) {
          totalMatches += cat.matches.length;
          completedMatches += cat.matches.filter(m => m.status === 'COMPLETED').length;
        }
        if (cat.podium?.first) championsCount++;
      });
    });

    return { totalCompetitors, totalMatches, completedMatches, championsCount };
  }, [baseTournaments]);

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Top Banner & Action */}
      <div className="bg-gradient-to-r from-amber-500/15 via-slate-900 to-slate-950 border border-amber-500/30 rounded-3xl p-5 sm:p-6 text-white shadow-xl flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="space-y-1.5">
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded-full bg-amber-500 text-slate-950 font-black text-[10px] uppercase tracking-wider">
              {canCreate ? 'Chaveamento & Torneios Internos 🏆' : 'Chaves do Campeonato 🏆'}
            </span>
          </div>
          <h2 className="text-xl sm:text-2xl font-black text-slate-100 flex items-center gap-2">
            <Trophy className="w-6 h-6 text-amber-400 stroke-[2.5]" />
            <span>Campeonatos Internos da Academia</span>
          </h2>
          <p className="text-xs sm:text-sm text-slate-300 max-w-xl">
            {canCreate 
              ? 'Crie divisões de peso e graduação, organize inscrições de alunos e gerencie chaves eliminatórias completas com pódio oficial e cronômetro integrado.'
              : 'Acompanhe as chaves oficiais, confrontos do tatame e resultados dos campeonatos internos da academia em tempo real.'}
          </p>
        </div>

        {canCreate && (
          <button
            onClick={() => setIsNewTournamentModalOpen(true)}
            className="px-5 py-3 rounded-2xl bg-amber-500 hover:bg-amber-400 text-slate-950 font-black text-xs transition-all shadow-lg active:scale-95 cursor-pointer flex items-center gap-2 shrink-0"
          >
            <Plus className="w-4 h-4 stroke-[3]" />
            <span>Criar Novo Campeonato</span>
          </button>
        )}
      </div>

      {/* Metrics Bar */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800 flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-amber-500/10 border border-amber-500/30 flex items-center justify-center text-amber-400">
            <Trophy className="w-5 h-5" />
          </div>
          <div>
            <p className="text-[10px] font-black uppercase text-slate-400">Torneios</p>
            <p className="text-lg font-black text-slate-100">{tournaments.length}</p>
          </div>
        </div>

        <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800 flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-blue-500/10 border border-blue-500/30 flex items-center justify-center text-blue-400">
            <Users className="w-5 h-5" />
          </div>
          <div>
            <p className="text-[10px] font-black uppercase text-slate-400">Inscrições</p>
            <p className="text-lg font-black text-slate-100">{metrics.totalCompetitors}</p>
          </div>
        </div>

        <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800 flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-purple-500/10 border border-purple-500/30 flex items-center justify-center text-purple-400">
            <Swords className="w-5 h-5" />
          </div>
          <div>
            <p className="text-[10px] font-black uppercase text-slate-400">Lutas nas Chaves</p>
            <p className="text-lg font-black text-slate-100">{metrics.completedMatches} / {metrics.totalMatches}</p>
          </div>
        </div>

        <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800 flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
            <Sparkles className="w-5 h-5" />
          </div>
          <div>
            <p className="text-[10px] font-black uppercase text-slate-400">Campeões Coroados</p>
            <p className="text-lg font-black text-slate-100">{metrics.championsCount}</p>
          </div>
        </div>
      </div>

      {/* Filter & Search Bar */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-3">
        <div className="flex items-center gap-1.5 overflow-x-auto max-w-full pb-1">
          {[
            { id: 'ALL', label: 'Todos os Torneios' },
            { id: 'IN_PROGRESS', label: 'Em Andamento ⚔️' },
            { id: 'REGISTRATION', label: 'Inscrições Abertas 📝' },
            { id: 'COMPLETED', label: 'Finalizados 🏆' },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setStatusFilter(tab.id as any)}
              className={`px-3 py-1.5 rounded-xl font-bold text-xs whitespace-nowrap transition-all cursor-pointer ${
                statusFilter === tab.id
                  ? 'bg-amber-500 text-slate-950 font-black shadow-sm'
                  : 'bg-slate-900 text-slate-400 hover:text-slate-200 border border-slate-800'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        <div className="relative w-full sm:w-64">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            placeholder="Buscar campeonato..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-9 pr-3 py-1.5 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-amber-500"
          />
        </div>
      </div>

      {/* Tournaments Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {filteredTournaments.map((tournament) => {
          const totalCompetitors = tournament.categories.reduce((acc, cat) => acc + cat.competitors.length, 0);
          const totalMatches = tournament.categories.reduce((acc, cat) => acc + (cat.matches?.length || 0), 0);
          const completedMatches = tournament.categories.reduce((acc, cat) => acc + (cat.matches?.filter(m => m.status === 'COMPLETED').length || 0), 0);
          const progressPercent = totalMatches > 0 ? Math.round((completedMatches / totalMatches) * 100) : 0;

          return (
            <div
              key={tournament.id}
              onClick={() => onSelectTournament(tournament)}
              className="bg-slate-900/90 border border-slate-800 hover:border-amber-500/60 rounded-3xl p-5 sm:p-6 text-white shadow-lg transition-all hover:-translate-y-0.5 space-y-4 cursor-pointer flex flex-col justify-between"
            >
              <div className="space-y-3">
                {/* Header pills */}
                <div className="flex items-center justify-between gap-2">
                  <div className="flex items-center gap-1.5 flex-wrap">
                    <span className={`px-2.5 py-0.5 rounded-full font-black text-[10px] uppercase tracking-wider ${
                      tournament.status === 'COMPLETED'
                        ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30'
                        : tournament.status === 'IN_PROGRESS'
                        ? 'bg-amber-500/20 text-amber-300 border border-amber-500/30'
                        : 'bg-blue-500/20 text-blue-300 border border-blue-500/30'
                    }`}>
                      {tournament.status === 'COMPLETED' ? 'Finalizado 🏁' : tournament.status === 'IN_PROGRESS' ? 'Em Andamento ⚔️' : 'Inscrições Abertas 📝'}
                    </span>

                    <span className="px-2.5 py-0.5 rounded-full bg-slate-800 text-slate-300 font-bold text-[10px] uppercase tracking-wider">
                      {tournament.modality === 'BOTH' ? 'Gi & No-Gi' : tournament.modality === 'GI' ? 'Gi (Kimono)' : 'No-Gi'}
                    </span>
                  </div>

                  {canCreate && (
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation();
                        setConfirmDeleteDialog({
                          isOpen: true,
                          tournamentId: tournament.id,
                          tournamentTitle: tournament.title,
                        });
                      }}
                      className="p-1.5 rounded-lg bg-slate-800/80 hover:bg-red-500/20 text-slate-400 hover:text-red-400 transition-colors cursor-pointer border border-slate-700/60"
                      title="Excluir Campeonato"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  )}
                </div>

                {/* Title */}
                <div>
                  <h3 className="font-extrabold text-base text-slate-100 hover:text-amber-400 transition-colors">
                    {tournament.title}
                  </h3>
                  {tournament.description && (
                    <p className="text-xs text-slate-400 line-clamp-2 mt-1">
                      {tournament.description}
                    </p>
                  )}
                </div>

                {/* Info row */}
                <div className="flex items-center gap-3 text-xs text-slate-300 flex-wrap">
                  <div className="flex items-center gap-1.5">
                    <Calendar className="w-3.5 h-3.5 text-amber-400" />
                    <span>{new Date(tournament.date).toLocaleDateString('pt-BR')}</span>
                  </div>
                  {tournament.time && (
                    <div className="flex items-center gap-1.5">
                      <Clock className="w-3.5 h-3.5 text-amber-400" />
                      <span>{tournament.time}</span>
                    </div>
                  )}
                  {tournament.location && (
                    <div className="flex items-center gap-1.5">
                      <MapPin className="w-3.5 h-3.5 text-amber-400" />
                      <span className="truncate max-w-[140px]">{tournament.location}</span>
                    </div>
                  )}
                </div>

                {/* Categories badges */}
                <div className="space-y-1.5">
                  <span className="text-[10px] font-black uppercase text-slate-400 block">
                    Categorias ({tournament.categories.length}):
                  </span>
                  <div className="flex flex-wrap gap-1.5">
                    {tournament.categories.map((cat) => (
                      <span
                        key={cat.id}
                        className="px-2 py-0.5 rounded-lg bg-slate-950 border border-slate-800 text-[11px] text-slate-300 flex items-center gap-1 font-medium"
                      >
                        <Layers className="w-3 h-3 text-amber-400" />
                        <span>{cat.name}</span>
                        <span className="text-[9px] text-amber-400 font-bold">({cat.competitors.length})</span>
                      </span>
                    ))}
                  </div>
                </div>
              </div>

              {/* Bottom Progress & Action */}
              <div className="pt-3 border-t border-slate-800 space-y-2">
                {totalMatches > 0 && (
                  <div className="space-y-1">
                    <div className="flex items-center justify-between text-[10px] font-bold text-slate-400">
                      <span>Progresso das Chaves</span>
                      <span className="text-amber-400">{completedMatches}/{totalMatches} lutas ({progressPercent}%)</span>
                    </div>
                    <div className="w-full h-1.5 bg-slate-950 rounded-full overflow-hidden border border-slate-800">
                      <div
                        className="h-full bg-amber-500 rounded-full transition-all"
                        style={{ width: `${progressPercent}%` }}
                      />
                    </div>
                  </div>
                )}

                <div className="flex items-center justify-between text-xs pt-1">
                  <span className="text-slate-400 font-medium">
                    {totalCompetitors} atletas inscritos
                  </span>
                  <span className="font-extrabold text-amber-400 flex items-center gap-1 group-hover:translate-x-1 transition-transform">
                    <span>Acessar Chaveamento</span>
                    <ChevronRight className="w-4 h-4" />
                  </span>
                </div>
              </div>
            </div>
          );
        })}

        {filteredTournaments.length === 0 && (
          <div className="col-span-full p-8 rounded-3xl bg-slate-900 border border-slate-800 text-center space-y-3">
            <Trophy className="w-8 h-8 text-slate-500 mx-auto" />
            <h4 className="font-extrabold text-base text-slate-200">
              {canCreate ? 'Nenhum campeonato encontrado' : 'Nenhuma chave de campeonato ativa'}
            </h4>
            <p className="text-xs text-slate-400 max-w-sm mx-auto">
              {canCreate 
                ? 'Crie o primeiro campeonato interno da academia para começar as disputas e montar o chaveamento.'
                : 'As chaves oficiais dos confrontos aparecerão aqui assim que o professor realizar o chaveamento das categorias.'}
            </p>
            {canCreate && (
              <button
                onClick={() => setIsNewTournamentModalOpen(true)}
                className="px-4 py-2 rounded-xl bg-amber-500 text-slate-950 font-black text-xs inline-flex items-center gap-1.5 cursor-pointer"
              >
                <Plus className="w-4 h-4 stroke-[3]" />
                <span>Criar Campeonato Agora</span>
              </button>
            )}
          </div>
        )}
      </div>

      {/* New Tournament Modal */}
      {isNewTournamentModalOpen && (
        <NewTournamentModal
          onClose={() => setIsNewTournamentModalOpen(false)}
          onCreateTournament={(t) => {
            const created = createTournament(t);
            onSelectTournament(created);
          }}
        />
      )}

      {/* Confirmation Modal for Delete (Iframe-Safe) */}
      {confirmDeleteDialog.isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-fade-in">
          <div className="bg-slate-900 border border-slate-800 rounded-3xl max-w-md w-full p-6 space-y-5 shadow-2xl animate-scale-in">
            <div className="flex items-start gap-4">
              <div className="p-3 rounded-2xl bg-red-500/15 border border-red-500/30 text-red-400 shrink-0">
                <Trash2 className="w-6 h-6" />
              </div>
              <div className="space-y-1">
                <h3 className="text-base font-extrabold text-slate-100">
                  Excluir Campeonato
                </h3>
                <p className="text-xs text-slate-300 leading-relaxed">
                  Tem certeza que deseja excluir o campeonato <strong className="text-white">"{confirmDeleteDialog.tournamentTitle}"</strong>? Todos os dados, chaves e inscrições serão removidos permanentemente.
                </p>
              </div>
            </div>

            <div className="flex items-center justify-end gap-2.5 pt-2 border-t border-slate-800">
              <button
                type="button"
                onClick={() => setConfirmDeleteDialog({ isOpen: false, tournamentId: '', tournamentTitle: '' })}
                className="px-4 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 font-bold text-xs transition-colors cursor-pointer"
              >
                Cancelar
              </button>
              <button
                type="button"
                onClick={() => {
                  if (confirmDeleteDialog.tournamentId) {
                    deleteTournament(confirmDeleteDialog.tournamentId);
                  }
                  setConfirmDeleteDialog({ isOpen: false, tournamentId: '', tournamentTitle: '' });
                }}
                className="px-4 py-2.5 rounded-xl bg-red-500 hover:bg-red-600 text-white font-black text-xs transition-all shadow-md active:scale-95 cursor-pointer"
              >
                Sim, Excluir Torneio
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
